/* ── Shared types for Error Notebook ── */

/** Deep AI explanation cached in DB */
export type DeepExplanationData = {
  whyWrong: string;
  whyCorrect: string;
  grammarRule: string;
  examples: string[];
  tip: string;
};

/** Core error entry from API */
export type ErrorEntry = {
  id: string;
  sourceModule: string;
  questionStem: string;
  options: string[] | null;
  userAnswer: string;
  correctAnswer: string;
  explanationEn: string | null;
  explanationVi: string | null;
  grammarTopic: string | null;
  isResolved: boolean;
  deepExplanation: DeepExplanationData | null;
  reviewCount: number;
  nextReviewAt: string | null;
  lastReviewedAt: string | null;
  createdAt: string;
};

/** Practice question generated by AI */
export type PracticeData = {
  questionStem: string;
  options: string[];
  correctIndex: number;
  explanation: string;
};

/** Drill exercise from AI */
export type DrillExercise = {
  type: string;
  instruction: string;
  data: Record<string, unknown>;
  targetWeakness: string;
  tip: string;
};

/** Drill session data */
export type DrillData = {
  exercises: DrillExercise[];
  summary: string;
  errorCount: number;
  topTopics: string[];
};

/** SRS grade (SM-2 scale) */
export type SRSGrade = 0 | 1 | 2 | 3 | 4 | 5;

/** SRS grade option for UI */
export type GradeOption = {
  grade: SRSGrade;
  label: string;
  emoji: string;
  color: string;
  desc: string;
};

export const SRS_GRADE_OPTIONS: GradeOption[] = [
  { grade: 0, label: "Quên hết", emoji: "😵", color: "var(--error)", desc: "Không nhớ gì" },
  { grade: 2, label: "Mơ hồ", emoji: "🤔", color: "var(--warning, var(--warning))", desc: "Nhớ mang máng" },
  { grade: 4, label: "Nhớ", emoji: "😊", color: "var(--success)", desc: "Nhớ được" },
  { grade: 5, label: "Dễ dàng", emoji: "🎯", color: "var(--accent)", desc: "Rất dễ nhớ" },
];

/** Module label mapping */
export const MODULE_LABELS: Record<string, string> = {
  "grammar-quiz": "Ngữ pháp",
  "grammar-lessons": "Bài học",
  "mock-test": "Thi thử",
  "daily-challenge": "Thử thách",
  listening: "Nghe",
  "toeic-practice": "TOEIC Luyện",
  "toeic-mock-test": "TOEIC Mock",
  "toeic-diagnostic": "TOEIC Diag",
  "toeic-drill": "TOEIC Drill",
  "writing-practice": "Viết",
};

/** Module icon mapping */
export const MODULE_ICONS: Record<string, string> = {
  "grammar-quiz": "📝",
  "grammar-lessons": "📖",
  "mock-test": "🎯",
  "daily-challenge": "⚡",
  listening: "🎧",
  "toeic-practice": "📋",
  "toeic-mock-test": "🏆",
  "toeic-diagnostic": "🔍",
  "toeic-drill": "💪",
  "writing-practice": "✍️",
};

/** Filter state */
export type ErrorFilters = {
  module: string;
  topic: string;
  resolved: string; // "true" | "false" | ""
  search: string;
};

export const INITIAL_FILTERS: ErrorFilters = {
  module: "",
  topic: "",
  resolved: "false",
  search: "",
};

export const FILTER_RESOLVED_OPTIONS = [
  { value: "false", label: "Chưa nắm", icon: "⚠️" },
  { value: "true", label: "Đã hiểu", icon: "✅" },
  { value: "", label: "Tất cả", icon: "📋" },
] as const;

export const MODULE_FILTER_OPTIONS = [
  { value: "", label: "Tất cả" },
  { value: "grammar-quiz", label: "Ngữ pháp" },
  { value: "grammar-lessons", label: "Bài học" },
  { value: "mock-test", label: "Thi thử" },
  { value: "daily-challenge", label: "Thử thách" },
  { value: "listening", label: "Nghe" },
  { value: "toeic-practice", label: "TOEIC" },
  { value: "writing-practice", label: "Viết" },
] as const;

/** Tab keys */
export type ErrorNotebookTab = "overview" | "review" | "list" | "analysis";
