import {
  AlertTriangle,
  BookOpen,
  CheckCircle,
  ClipboardList,
  FileText,
  Flame,
  Frown,
  Headphones,
  HelpCircle,
  PenTool,

  Smile,
  Target,
  Trophy,
  Zap,
} from "lucide-react";

/* ── Shared types for Error Notebook ── */

/** Deep AI explanation cached in DB */
export type DeepExplanationData = {
  whyWrong: string;
  whyCorrect: string;
  grammarRule: string;
  examples: string[];
  tip: string;
};

/** Core error entry from API */
export type ErrorEntry = {
  id: string;
  sourceModule: string;
  questionStem: string;
  options: string[] | null;
  userAnswer: string;
  correctAnswer: string;
  explanationEn: string | null;
  explanationVi: string | null;
  grammarTopic: string | null;
  isResolved: boolean;
  deepExplanation: DeepExplanationData | null;
  reviewCount: number;
  nextReviewAt: string | null;
  lastReviewedAt: string | null;
  createdAt: string;
};

/** Practice question generated by AI */
export type PracticeData = {
  questionStem: string;
  options: string[];
  correctIndex: number;
  explanation: string;
};

/** Drill exercise from AI */
export type DrillExercise = {
  type: string;
  instruction: string;
  data: Record<string, unknown>;
  targetWeakness: string;
  tip: string;
};

/** Drill session data */
export type DrillData = {
  exercises: DrillExercise[];
  summary: string;
  errorCount: number;
  topTopics: string[];
};

/** SRS grade (SM-2 scale) */
export type SRSGrade = 0 | 1 | 2 | 3 | 4 | 5;

/** SRS grade option for UI */
export type GradeOption = {
  grade: SRSGrade;
  label: string;
  icon: React.ComponentType<{ className?: string; size?: number }>;
  color: string;
  desc: string;
};

export const SRS_GRADE_OPTIONS: GradeOption[] = [
  { grade: 0, label: "Forgot", icon: Frown, color: "var(--error)", desc: "No memory of this" },
  {
    grade: 2,
    label: "Vague",
    icon: HelpCircle,
    color: "var(--warning, var(--warning))",
    desc: "Partially remembered",
  },
  {
    grade: 4,
    label: "Remembered",
    icon: Smile,
    color: "var(--success)",
    desc: "Recalled with effort",
  },
  { grade: 5, label: "Easy", icon: Target, color: "var(--accent)", desc: "Perfectly easy recall" },
];

/** Module label mapping */
export const MODULE_LABELS: Record<string, string> = {
  "grammar-quiz": "Grammar",
  "grammar-lessons": "Lessons",
  "mock-test": "Mock Test",

  listening: "Listening",
  "toeic-practice": "TOEIC Practice",
  "toeic-mock-test": "TOEIC Mock",
  "toeic-drill": "TOEIC Drill",
  "writing-practice": "Writing",
};

/** Module icon mapping */
export const MODULE_ICONS: Record<
  string,
  React.ComponentType<{ className?: string; size?: number }>
> = {
  "grammar-quiz": FileText,
  "grammar-lessons": BookOpen,
  "mock-test": Target,

  listening: Headphones,
  "toeic-practice": ClipboardList,
  "toeic-mock-test": Trophy,
  "toeic-drill": Flame,
  "writing-practice": PenTool,
};

/** Filter state */
export type ErrorFilters = {
  module: string;
  topic: string;
  resolved: string; // "true" | "false" | ""
  search: string;
};

export const INITIAL_FILTERS: ErrorFilters = {
  module: "",
  topic: "",
  resolved: "false",
  search: "",
};

export const FILTER_RESOLVED_OPTIONS: {
  value: string;
  label: string;
  icon: React.ComponentType<{ className?: string; size?: number }>;
}[] = [
  { value: "false", label: "Unresolved", icon: AlertTriangle },
  { value: "true", label: "Resolved", icon: CheckCircle },
  { value: "", label: "All", icon: ClipboardList },
];

export const MODULE_FILTER_OPTIONS = [
  { value: "", label: "All" },
  { value: "grammar-quiz", label: "Grammar" },
  { value: "grammar-lessons", label: "Lessons" },
  { value: "mock-test", label: "Mock Test" },

  { value: "listening", label: "Listening" },
  { value: "toeic-practice", label: "TOEIC" },
  { value: "writing-practice", label: "Writing" },
] as const;

/** Tab keys */
export type ErrorNotebookTab = "overview" | "review" | "list" | "analysis";
