// scripts/generate-word-list.ts
// Run once with: npx tsx scripts/generate-word-list.ts

import { writeFileSync } from "fs";
import { join } from "path";

const URL =
  "https://raw.githubusercontent.com/dwyl/english-words/master/words_alpha.txt";

const text = await (await fetch(URL)).text();

const words = [
  ...new Set(
    text
      .split("\n")
      .map((w) => w.trim().toLowerCase())
      .filter((w) => w.length >= 2 && w.length <= 20 && /^[a-z][a-z'-]*$/.test(w)),
  ),
].sort();

const lines = [
  "// Auto-generated by scripts/generate-word-list.ts. Do not edit manually.",
  "export const ENGLISH_WORDS: readonly string[] = [",
  ...words.map((w) => `  "${w}",`),
  "];",
  "",
];

writeFileSync(join(process.cwd(), "data/english-words.ts"), lines.join("\n"));
console.log(`Generated ${words.length} words → data/english-words.ts`);
