// Seed script: npx tsx scripts/seed-reading-passages.ts
// Story 19.4.1, AC4 — seeds ≥30 CEFR-graded passages into reading_passage table.

import { readFileSync } from "fs";
import { Pool } from "pg";

// Manual env loading
const envContent = readFileSync(".env.local", "utf-8");
for (const line of envContent.split("\n")) {
  const t = line.trim();
  if (!t || t.startsWith("#")) continue;
  const eq = t.indexOf("=");
  if (eq === -1) continue;
  if (!process.env[t.slice(0, eq)]) process.env[t.slice(0, eq)] = t.slice(eq + 1);
}

const pool = new Pool({ connectionString: process.env.DATABASE_URL! });

type Passage = { title: string; body: string; cefrLevel: string; section: string };

// ── A2 Passages (150–250 words) ──
const A2: Passage[] = [
  { title: "My Daily Routine", section: "lifestyle", cefrLevel: "A2", body: `I wake up at seven o'clock every morning. First, I take a shower and brush my teeth. Then I eat breakfast. I usually have toast and orange juice. After breakfast, I go to work by bus. The bus stop is near my house. I work in an office from nine to five. At lunchtime, I eat a sandwich in the park if the weather is nice. After work, I go to the gym three times a week. I like running and swimming. In the evening, I cook dinner at home. I enjoy cooking Italian food, especially pasta. After dinner, I watch television or read a book. I usually go to bed at eleven o'clock. On weekends, I like to visit my friends or go shopping. Sometimes I go to the cinema to watch a new film. I also like walking in the park with my dog. His name is Max and he is very friendly. I think having a routine is important because it helps me feel organized and happy.` },
  { title: "Shopping at the Market", section: "lifestyle", cefrLevel: "A2", body: `Every Saturday morning, I go to the local market near my home. The market is very big and sells many different things. There are stalls with fresh fruit and vegetables, bread, cheese, and meat. I always buy apples, bananas, and carrots because they are healthy. The prices at the market are cheaper than in the supermarket. I also like to buy flowers for my kitchen table. The flower seller always smiles and says hello. Sometimes I buy fish from the fish stall. The fish is very fresh because it comes from the sea every morning. There is also a stall that sells clothes and shoes. Last week, I bought a nice blue scarf for winter. After shopping, I usually have a coffee at the small café next to the market. The coffee there is delicious and not expensive. I enjoy going to the market because I can talk to the sellers and see my neighbors. It is a nice way to start the weekend.` },
  { title: "A Visit to the Doctor", section: "health", cefrLevel: "A2", body: `Last week I felt sick, so I went to see the doctor. I had a headache and a sore throat. The doctor asked me some questions about my health. She took my temperature and looked at my throat. She said I had a cold and needed to rest. She told me to drink lots of water and hot tea with honey. She also gave me some medicine to take three times a day. I stayed at home for three days and slept a lot. My mother made soup for me because soup is good when you are sick. After three days, I started to feel better. I went back to work on Thursday. Now I always wash my hands often and eat healthy food to stay well. I think it is important to go to the doctor when you feel sick because they can help you get better quickly. I am happy I am healthy again now.` },
  { title: "My Favorite Holiday", section: "travel", cefrLevel: "A2", body: `Last summer, my family and I went on holiday to the beach. We drove for four hours to get there. We stayed in a small hotel near the sea. The hotel had a swimming pool and a restaurant. Every morning, we had breakfast at the hotel. Then we walked to the beach. The beach was beautiful with white sand and blue water. I love swimming in the sea. My children built sandcastles and played with a ball. In the afternoon, we ate ice cream and drank cold lemonade. One day, we took a boat trip to see dolphins. We saw five dolphins jumping in the water. It was amazing! In the evening, we went to different restaurants to try local food. The seafood was very delicious. We stayed for one week and had a wonderful time. I took many photos to remember the holiday. I want to go back next summer because it was the best holiday ever.` },
  { title: "Learning to Cook", section: "lifestyle", cefrLevel: "A2", body: `When I was young, I did not know how to cook. I always ate at restaurants or bought ready meals from the supermarket. One day, my friend invited me to her house for dinner. She cooked a wonderful meal and I was very impressed. I asked her to teach me how to cook. She showed me how to make simple dishes like fried rice and vegetable soup. At first, I made many mistakes. I burned the rice and put too much salt in the soup. But I did not give up. I practiced every weekend. I watched cooking videos on the internet and tried new recipes. Now I can cook many different dishes. My favorite thing to cook is chicken curry. My friends say my cooking is very good. I feel proud when people enjoy my food. Cooking is also cheaper and healthier than eating out. I think everyone should learn to cook basic meals. It is a very useful skill for life.` },
  { title: "My Best Friend", section: "lifestyle", cefrLevel: "A2", body: `My best friend is called Sarah. We met at school when we were ten years old. She sat next to me in class and we started talking. We discovered that we both liked reading and playing football. From that day, we became best friends. Sarah is very kind and always helps people. When I am sad, she makes me laugh. We talk on the phone every day and meet every weekend. We like to go to the cinema, eat pizza, and walk in the park together. Sometimes we study together for our exams. Sarah is very smart and good at mathematics. Last year, Sarah moved to a different city for her job. I was very sad, but we still talk every day using video calls. We visit each other every month. I think a good friend is someone who is always there for you, even when they are far away. Sarah is my best friend and I am very lucky to have her in my life.` },
  { title: "Public Transport in My City", section: "travel", cefrLevel: "A2", body: `In my city, there are many ways to travel. We have buses, trains, and a metro system. I usually take the bus to go to work. The bus comes every ten minutes and the ticket costs one dollar. The bus stops are close to my house and my office. Sometimes I take the metro when I need to go to the city center. The metro is faster than the bus, but it is more expensive. On weekends, I sometimes take the train to visit other cities. The train station is in the center of the city and has many lines. I like taking public transport because it is cheaper than driving a car. It is also better for the environment because fewer cars means less pollution. However, sometimes the buses are late or very crowded in the morning. I wish the government would add more buses during rush hour. Overall, I think the public transport in my city is quite good and most people use it every day.` },
];

// ── B1 Passages (200–350 words) ──
const B1: Passage[] = [
  { title: "The Benefits of Reading", section: "education", cefrLevel: "B1", body: `Reading is one of the most valuable activities a person can do. Whether you enjoy fiction, non-fiction, or magazines, reading offers numerous benefits for both the mind and body. Research shows that people who read regularly have better memory and concentration skills. When you read, your brain creates new neural pathways, which helps keep your mind sharp as you age. Reading also reduces stress. A study by the University of Sussex found that reading for just six minutes can reduce stress levels by up to 68 percent, making it more effective than listening to music or going for a walk. Furthermore, reading expands your vocabulary and improves your writing skills. The more you read, the more words you encounter, and these words inevitably make their way into your everyday language. For language learners especially, reading is an excellent way to improve fluency naturally. Another important benefit is empathy. When we read stories about different characters and their experiences, we develop a greater understanding of other people's feelings and perspectives. This makes us more compassionate in our daily interactions. Despite all these advantages, many people say they do not have time to read. However, even reading for fifteen to twenty minutes a day can make a significant difference. You could read during your commute, before bed, or during your lunch break. The key is to find books that genuinely interest you and to make reading a regular habit.` },
  { title: "Working from Home", section: "business", cefrLevel: "B1", body: `Since the global pandemic, working from home has become increasingly common. Many companies now offer remote work options, and some employees prefer to work entirely from home. There are several advantages to this arrangement. First, employees save time and money by not commuting. The average worker spends about forty-five minutes traveling to work each day, which adds up to many hours each month. Working from home also gives people more flexibility to manage their personal responsibilities, such as childcare or household tasks. However, remote work is not without its challenges. Many people find it difficult to separate their work life from their personal life when both happen in the same space. Some workers report feeling isolated because they miss the social interactions with colleagues. Communication can also be more difficult through emails and video calls compared to face-to-face conversations. To make remote work successful, experts recommend creating a dedicated workspace at home, setting clear boundaries between work hours and personal time, and maintaining regular communication with team members. Companies should also invest in good technology and provide training on how to work effectively from home. While remote work may not suit everyone, it is clear that it will remain an important part of the modern workplace.` },
  { title: "Climate Change and Food", section: "environment", cefrLevel: "B1", body: `Climate change is affecting food production around the world in many ways. Rising temperatures are changing growing seasons and making some regions too hot or too dry to farm. Extreme weather events such as floods, droughts, and storms are destroying crops more frequently than before. Scientists predict that global crop yields could decline by up to twenty-five percent by 2050 if current trends continue. This is particularly concerning because the world's population is expected to reach nearly ten billion by that time, meaning we will need to produce more food, not less. Some crops are more vulnerable than others. For example, wheat, rice, and maize are all sensitive to temperature changes. Coffee production is also threatened, with studies suggesting that half of the land currently used to grow coffee could become unsuitable by 2050. To address these challenges, farmers are adopting new techniques such as drought-resistant crop varieties, improved irrigation systems, and precision agriculture using technology. Consumers can also help by reducing food waste, eating more plant-based meals, and buying locally produced food. Governments need to invest in agricultural research and support farmers in adapting to changing conditions. The relationship between climate change and food security is complex, but finding solutions is essential for feeding future generations.` },
  { title: "The History of Coffee", section: "general", cefrLevel: "B1", body: `Coffee is the most popular drink in the world after water, with over two billion cups consumed every day. But where did this beloved drink come from? According to legend, coffee was discovered in Ethiopia around the ninth century by a goat herder named Kaldi. He noticed that his goats became very energetic after eating berries from a certain tree. Curious, he tried the berries himself and felt a similar boost of energy. The knowledge of these energizing berries spread to monks in nearby monasteries, who used them to stay awake during long hours of prayer. By the fifteenth century, coffee was being cultivated in Yemen, and coffeehouses began appearing across the Middle East. These coffeehouses became important social gathering places where people discussed politics, business, and culture. Coffee reached Europe in the seventeenth century and quickly became popular. Some people were suspicious of the new drink at first, but it soon replaced beer and wine as the preferred morning beverage. Today, coffee is grown in over seventy countries, primarily in tropical regions near the equator. Brazil is the world's largest producer, followed by Vietnam and Colombia. The coffee industry employs millions of people worldwide and continues to evolve with new brewing methods and specialty varieties.` },
  { title: "Social Media and Mental Health", section: "technology", cefrLevel: "B1", body: `Social media has transformed the way we communicate and share information. Platforms like Instagram, TikTok, and Twitter connect billions of people worldwide. However, researchers are increasingly concerned about the impact of social media on mental health, particularly among young people. Studies have shown that excessive use of social media can lead to feelings of anxiety, depression, and loneliness. One reason is social comparison. When people see carefully curated images of others' lives, they may feel that their own life is not good enough. This can damage self-esteem and create unrealistic expectations. Another concern is cyberbullying, which can have devastating effects on victims. Additionally, the constant notifications and updates from social media platforms can disrupt sleep patterns and reduce attention spans. However, social media also has positive aspects. It allows people to maintain relationships with friends and family who live far away, provides access to educational content, and helps people find communities with shared interests. The key is to use social media mindfully. Experts recommend limiting screen time, unfollowing accounts that make you feel bad, and taking regular breaks from social media. Parents should also talk to their children about safe and healthy online habits. Finding the right balance is essential for enjoying the benefits while minimizing the risks.` },
  { title: "Volunteering Abroad", section: "travel", cefrLevel: "B1", body: `Every year, thousands of people travel to other countries to volunteer. They teach English, build houses, protect wildlife, or help with healthcare projects. Volunteering abroad can be an incredibly rewarding experience that changes both the volunteer and the community they serve. One of the biggest benefits is cultural exchange. Volunteers learn about different customs, traditions, and ways of life while sharing their own culture. This promotes understanding and breaks down stereotypes. Volunteering also develops valuable skills such as teamwork, problem-solving, and communication in challenging environments. However, there are some concerns about volunteer tourism. Critics argue that unskilled volunteers can sometimes do more harm than good. For example, when untrained volunteers build houses, the quality may be poor, and their work could take jobs away from local builders. Some volunteer programs are also criticized for being exploitative, charging high fees while providing little benefit to local communities. To volunteer responsibly, it is important to research organizations carefully, choose programs that align with your skills, and commit to a meaningful period of time rather than just a few days. The most effective volunteer programs work alongside local communities and prioritize their needs.` },
  { title: "The Importance of Sleep", section: "health", cefrLevel: "B1", body: `Sleep is one of the most important things for our health, yet many people do not get enough of it. Health experts recommend that adults sleep between seven and nine hours each night. Unfortunately, studies show that about one third of adults regularly sleep less than six hours. Lack of sleep can have serious consequences. It weakens the immune system, making us more likely to catch colds and other illnesses. It also affects our ability to concentrate, remember information, and make good decisions. Chronic sleep deprivation has been linked to serious conditions such as heart disease, diabetes, and obesity. Sleep is also crucial for emotional well-being. People who do not sleep enough are more likely to experience mood swings, irritability, and symptoms of depression. There are several things you can do to improve your sleep quality. First, try to go to bed and wake up at the same time every day, even on weekends. This helps regulate your body's internal clock. Avoid caffeine and alcohol in the evening, as both can interfere with sleep. Make your bedroom dark, quiet, and cool. Try not to use screens such as phones or laptops for at least an hour before bed, as the blue light they emit can disrupt your natural sleep cycle.` },
];

// ── B2 Passages (250–450 words) ──
const B2: Passage[] = [
  { title: "The Ethics of Artificial Intelligence", section: "technology", cefrLevel: "B2", body: `Artificial intelligence is rapidly transforming virtually every aspect of modern society, from healthcare diagnostics to autonomous vehicles, from financial trading to creative endeavors. As these technologies become increasingly sophisticated, they raise profound ethical questions that society must urgently address. One of the most pressing concerns is algorithmic bias. AI systems are trained on historical data, which often reflects existing societal prejudices. When these biased datasets are used to train algorithms that make decisions about hiring, lending, or criminal sentencing, they can perpetuate and even amplify discrimination against marginalized groups. For instance, research has demonstrated that facial recognition systems are significantly less accurate when identifying people of color, which has serious implications for law enforcement applications. Another critical issue is transparency. Many modern AI systems, particularly deep learning models, operate as "black boxes" — their decision-making processes are opaque even to their creators. This lack of explainability is problematic when AI is used in high-stakes domains such as healthcare or criminal justice, where individuals have a right to understand why a particular decision was made about them. The question of accountability is equally complex. When an autonomous vehicle causes an accident, or an AI-powered medical system provides an incorrect diagnosis, determining who bears responsibility becomes extraordinarily challenging. Is it the developer who created the algorithm, the company that deployed it, or the user who relied on its recommendations? Privacy represents yet another dimension of the ethical landscape. AI systems often require vast amounts of personal data to function effectively, raising concerns about surveillance and the erosion of individual privacy. The development of deepfake technology, which can create convincingly realistic but entirely fabricated audio and video content, poses additional threats to trust and truth in public discourse. Addressing these challenges requires a multifaceted approach involving technologists, ethicists, policymakers, and the public.` },
  { title: "Urbanization and Sustainable Cities", section: "environment", cefrLevel: "B2", body: `For the first time in human history, more than half of the world's population lives in cities, and this proportion is projected to increase to nearly seventy percent by 2050. This unprecedented wave of urbanization presents both remarkable opportunities and daunting challenges for sustainability. Cities are engines of economic growth and innovation, generating over eighty percent of global GDP. They offer residents better access to education, healthcare, and cultural amenities compared to rural areas. The concentration of people and services in urban areas can also be more environmentally efficient in certain respects — per capita carbon emissions in dense cities like New York or Tokyo are often lower than national averages because residents rely more on public transportation and live in smaller, energy-efficient apartments. However, the environmental footprint of cities is enormous. Urban areas consume over seventy-five percent of global energy and produce more than seventy percent of carbon dioxide emissions. Rapid, unplanned urbanization in developing countries frequently results in sprawling slums with inadequate sanitation, clean water access, and transportation infrastructure. Air pollution in many major cities exceeds safe levels, contributing to millions of premature deaths annually. The concept of sustainable cities aims to address these challenges through integrated planning and innovative solutions. Green building standards, renewable energy adoption, efficient public transportation networks, urban agriculture, and smart waste management systems are all components of this vision. Cities like Copenhagen, Singapore, and Curitiba have become models of sustainable urban development. Copenhagen aims to become carbon neutral by 2025, while Singapore has pioneered vertical gardens and comprehensive water recycling systems. Achieving truly sustainable urbanization will require unprecedented cooperation between governments, businesses, and citizens.` },
  { title: "The Psychology of Decision Making", section: "science", cefrLevel: "B2", body: `Every day, the average person makes approximately 35,000 decisions, ranging from trivial choices about what to eat for breakfast to consequential judgments about career moves and relationships. Understanding how we make these decisions — and why we often make poor ones — has been a central focus of psychological research for decades. Traditional economic theory assumed that humans are rational agents who carefully weigh costs and benefits before making decisions. However, groundbreaking work by psychologists Daniel Kahneman and Amos Tversky revealed that human decision-making is systematically influenced by cognitive biases — mental shortcuts that can lead us astray. One of the most well-documented biases is the anchoring effect, which occurs when an initial piece of information disproportionately influences subsequent judgments. For example, when negotiating a salary, the first number mentioned tends to anchor the entire discussion, regardless of whether that number is reasonable. Confirmation bias is another pervasive tendency — we naturally seek out information that confirms our existing beliefs while ignoring contradictory evidence. Loss aversion describes our tendency to feel the pain of losing something approximately twice as strongly as the pleasure of gaining something of equivalent value. This asymmetry can lead to irrational behavior, such as holding onto losing investments far too long or refusing to sell a house below its original purchase price despite changing market conditions. The availability heuristic causes us to overestimate the probability of events that are easily recalled, which is why many people fear flying more than driving despite the latter being statistically far more dangerous. Understanding these biases does not automatically eliminate them, but awareness can help us develop strategies to make better decisions, such as seeking diverse perspectives, considering the opposite viewpoint, and sleeping on important choices.` },
  { title: "The Future of Work", section: "business", cefrLevel: "B2", body: `The nature of work is undergoing a fundamental transformation driven by technological advancement, demographic shifts, and evolving social expectations. Automation and artificial intelligence are expected to displace millions of jobs in the coming decades while simultaneously creating new roles that we cannot yet envision. According to the World Economic Forum, by 2025 machines were projected to perform more current work tasks than humans, but this technological displacement would be offset by the creation of 97 million new roles better adapted to the new division of labor between humans, machines, and algorithms. The gig economy represents another significant shift in how people work. Platforms like Uber, Upwork, and Deliveroo have created unprecedented flexibility for workers who prefer non-traditional employment arrangements. However, this flexibility often comes at the cost of job security, benefits, and predictable income. The debate over how to regulate these platforms while preserving their benefits remains unresolved in most countries. Skills requirements are changing rapidly as well. Critical thinking, creativity, emotional intelligence, and technological literacy are increasingly valued over routine technical expertise that can be automated. Lifelong learning has become essential rather than optional, as workers may need to reinvent their careers multiple times over a working life that could span fifty or more years. Organizations are also rethinking fundamental assumptions about how and where work happens. The widespread adoption of remote and hybrid work arrangements during the pandemic demonstrated that many knowledge workers can be equally or more productive outside traditional office environments.` },
  { title: "Biodiversity Loss and Conservation", section: "environment", cefrLevel: "B2", body: `The Earth is experiencing what many scientists describe as its sixth mass extinction event, with species disappearing at a rate approximately one thousand times higher than the natural background rate. Unlike the five previous mass extinctions, which were caused by natural phenomena such as asteroid impacts or volcanic activity, the current crisis is driven almost entirely by human activities. Habitat destruction is the primary driver of biodiversity loss. Forests, wetlands, and grasslands are being converted for agriculture, urban development, and resource extraction at an alarming pace. The Amazon rainforest, which harbors approximately ten percent of all known species, has lost roughly seventeen percent of its forest cover in the past fifty years. Climate change compounds these threats by altering ecosystems faster than many species can adapt, while pollution contaminates air, water, and soil on a global scale. The consequences of biodiversity loss extend far beyond the intrinsic value of individual species. Ecosystems provide essential services that underpin human civilization, including pollination of food crops, water purification, climate regulation, and flood control. These ecosystem services have been valued at an estimated 125 trillion dollars annually — roughly one and a half times global GDP. The pharmaceutical industry also depends heavily on biodiversity, with many important medicines derived from natural compounds found in plants, fungi, and animals. Conservation efforts are making a difference in some areas. Protected areas now cover approximately fifteen percent of the world's land surface, and international agreements like the Convention on Biological Diversity aim to coordinate global action. However, significantly greater investment and political commitment are needed to reverse the current trajectory.` },
  { title: "The Science of Habits", section: "science", cefrLevel: "B2", body: `Habits shape approximately forty percent of our daily behavior, yet we rarely think about how they form or how to change them. Understanding the science behind habits can help us build positive routines and break destructive patterns. Neuroscientists have identified a three-part loop that underlies every habit. First, there is a cue — a trigger that tells your brain to go into automatic mode. This could be a time of day, a location, an emotional state, or the presence of certain people. Second, there is the routine — the behavior itself, which can be physical, mental, or emotional. Third, there is the reward — a positive feeling that reinforces the loop and tells your brain this pattern is worth remembering. This loop operates in the basal ganglia, a primitive part of the brain that controls automatic behaviors, which explains why habits persist even when we consciously want to change them. The key to changing a habit is not to fight the cue or eliminate the reward, but to substitute the routine. For example, if you habitually eat chocolate when you feel stressed at work, you can keep the cue (stress) and the reward (a brief mood boost) but replace the routine with a healthier alternative, such as taking a short walk or doing breathing exercises. Research also shows that willpower alone is insufficient for lasting behavior change. Environmental design — structuring your surroundings to make good habits easier and bad habits harder — is far more effective. This might mean keeping healthy snacks visible in your kitchen while placing unhealthy ones out of sight, or placing your running shoes by the door the night before a planned morning run.` },
];

// ── C1 Passages (350–600 words) ──
const C1: Passage[] = [
  { title: "The Paradox of Choice in Modern Consumer Society", section: "business", cefrLevel: "C1", body: `In his seminal 2004 work "The Paradox of Choice," psychologist Barry Schwartz articulated a counterintuitive proposition that has since been substantiated by extensive research: an abundance of options, far from enhancing well-being and satisfaction, frequently produces anxiety, decision paralysis, and diminished contentment with the choices ultimately made. This phenomenon has profound implications for understanding consumer behavior in contemporary societies characterized by unprecedented material abundance. Consider the simple act of purchasing a pair of jeans. Whereas consumers in previous generations might have chosen between two or three options at a local department store, today's shopper confronts a bewildering array of styles, fits, fabrics, washes, and price points across dozens of brands, both online and in physical stores. Schwartz distinguished between two cognitive types that respond differently to this abundance: "maximizers," who exhaustively evaluate all available options seeking the objectively best choice, and "satisficers," who set minimum acceptable criteria and select the first option meeting those thresholds. Research consistently demonstrates that maximizers experience greater regret, lower satisfaction, and more depression than satisficers, even when their objective outcomes are superior. The proliferation of choice extends well beyond consumer goods into domains with far greater existential significance — career paths, romantic partners, living arrangements, and educational trajectories. The democratization of opportunity, while undeniably positive in aggregate, imposes what existentialist philosophers might recognize as the burden of freedom: the anxiety that accompanies the awareness that we are the architects of our own lives and that every choice necessarily forecloses alternative possibilities. Several strategies can mitigate the negative effects of excessive choice. Deliberately limiting the options one considers, establishing clear decision criteria before beginning the evaluation process, practicing gratitude for what one has chosen rather than ruminating about rejected alternatives, and reducing exposure to information about options not chosen can all help preserve satisfaction and mental well-being in an age of abundance.` },
  { title: "Neuroplasticity and Lifelong Learning", section: "science", cefrLevel: "C1", body: `For much of the twentieth century, the prevailing orthodoxy in neuroscience held that the adult brain was essentially fixed — a static organ whose neural architecture was established during critical developmental periods in childhood and adolescence, after which it could only deteriorate. This dogma has been comprehensively overturned by research into neuroplasticity, the brain's remarkable capacity to reorganize itself by forming new neural connections throughout life. The implications for education, rehabilitation, and cognitive enhancement are revolutionary. Neuroplasticity operates through several mechanisms. Synaptic plasticity involves the strengthening or weakening of existing connections between neurons based on activity patterns — the neurological basis of the adage "neurons that fire together wire together." Structural plasticity encompasses more dramatic changes, including the growth of new dendrites, the formation of entirely new synaptic connections, and even neurogenesis — the birth of new neurons — in specific brain regions, particularly the hippocampus, which is central to memory formation. Critically, these processes are experience-dependent, meaning that the specific ways in which we use our brains literally shape their physical structure. London taxi drivers, who must memorize the city's labyrinthine street layout, have been shown to possess significantly larger posterior hippocampi than control subjects. Musicians who begin training in childhood develop enhanced connectivity between brain regions involved in auditory processing, motor control, and spatial reasoning. Multilingual individuals demonstrate increased gray matter density in language-related areas and exhibit superior executive function capabilities. These findings have profound implications for education across the lifespan. They provide a neurobiological foundation for the concept of lifelong learning, demonstrating that cognitive development need not plateau in early adulthood. For individuals recovering from brain injuries, neuroplasticity offers hope that undamaged regions can assume functions previously performed by damaged areas, provided appropriate and intensive rehabilitation is undertaken.` },
  { title: "The Attention Economy", section: "technology", cefrLevel: "C1", body: `In an era of information superabundance, the scarcest resource is no longer information itself but the human attention required to process it. This fundamental insight underpins what economists and technologists term the "attention economy" — a framework for understanding the competitive dynamics of modern media, advertising, and technology industries where capturing and monetizing human attention has become the primary commercial imperative. The concept, first articulated by Herbert Simon in 1971, has acquired unprecedented relevance in the digital age, where the average person is estimated to encounter between 6,000 and 10,000 advertisements daily and where technology platforms compete relentlessly for every available moment of cognitive engagement. The business models of the world's most valuable technology companies — Google, Meta, TikTok, and their counterparts — are fundamentally predicated on harvesting attention at scale and converting it into advertising revenue. These platforms employ sophisticated algorithmic systems designed to maximize engagement, leveraging insights from behavioral psychology to exploit cognitive vulnerabilities. Variable reward schedules, social validation mechanisms, and infinite scrolling interfaces are not accidental design choices but deliberately engineered features that activate dopaminergic pathways associated with compulsive behavior. The consequences of this attention extraction extend beyond individual productivity and well-being into the realm of democratic governance. When citizens' attention is fragmented and directed toward sensationalized content optimized for engagement rather than accuracy, the epistemic foundations of informed democratic participation are undermined. The proliferation of misinformation and the polarization of political discourse can be understood, at least in part, as byproducts of attention-maximizing algorithms that prioritize emotionally provocative content because it generates more engagement. Regulatory responses are beginning to emerge across jurisdictions, though they remain fragmented and frequently lag behind technological developments.` },
  { title: "The Philosophy of Language", section: "education", cefrLevel: "C1", body: `The relationship between language and thought has been a subject of philosophical inquiry since antiquity, but it acquired renewed urgency in the twentieth century with the emergence of linguistic relativity as a testable hypothesis. The strong version of this hypothesis, associated with Benjamin Lee Whorf, posits that the structure of a language determines its speakers' worldview and cognition. While the strong formulation has been largely discredited, a weaker version — that language influences certain aspects of thought and perception — has garnered substantial empirical support. Consider the domain of color perception. Languages differ considerably in how they divide the color spectrum into named categories. Russian, for instance, distinguishes lexically between light blue and dark blue as fundamentally different colors, and experimental research has demonstrated that Russian speakers are measurably faster at discriminating between shades that cross this linguistic boundary than English speakers, for whom both fall under the single category of blue. Similarly, research with speakers of Kuuk Thaayorre, an Aboriginal Australian language that uses cardinal directions rather than relative spatial terms, has shown that their speakers maintain an extraordinary awareness of orientation. These findings suggest that while language does not imprison thought within rigid categories, it does create cognitive habits and attentional biases that subtly shape how we perceive and interact with the world. The implications extend beyond academic curiosity into practical domains such as cross-cultural communication, translation theory, and even artificial intelligence.` },
  { title: "Epistemic Humility in the Age of Information", section: "education", cefrLevel: "C1", body: `In an age characterized by the democratization of information and the proliferation of confident opinion, the intellectual virtue of epistemic humility — the recognition that our knowledge is always incomplete and potentially mistaken — has never been more important or more difficult to practice. Epistemic humility does not entail radical skepticism or intellectual paralysis; rather, it involves calibrating one's confidence to the strength of available evidence and remaining genuinely open to revising one's beliefs in light of new information. The challenge of maintaining epistemic humility is compounded by several well-documented cognitive tendencies. The Dunning-Kruger effect describes the paradoxical finding that individuals with the least knowledge in a domain tend to overestimate their competence most dramatically, while genuine experts are more likely to recognize the limits of their understanding. Confirmation bias leads us to seek out and preferentially weight information that confirms our preexisting beliefs while dismissing or rationalizing contradictory evidence. Social media algorithms exacerbate these tendencies by creating informational echo chambers that reinforce existing worldviews. The practice of epistemic humility requires deliberate cultivation. It involves actively seeking out perspectives that challenge one's own, distinguishing between the strength of one's feelings about a proposition and the quality of evidence supporting it, and developing comfort with uncertainty and ambiguity. In professional contexts, fostering a culture of epistemic humility can improve decision-making quality, encourage productive dissent, and reduce the likelihood of catastrophic errors driven by overconfidence.` },
];

// ── Extra A2 passages to reach ≥30 ──
const A2_EXTRA: Passage[] = [
  { title: "My Neighborhood", section: "lifestyle", cefrLevel: "A2", body: `I live in a quiet neighborhood in the city. There are many houses and a few apartment buildings on my street. Near my house, there is a small park where children play every afternoon. There is also a bakery that makes fresh bread every morning. I can smell the bread from my kitchen window. Next to the bakery, there is a pharmacy and a small supermarket. I buy my groceries there because it is very convenient. The people in my neighborhood are very friendly. My neighbor Mrs. Chen always says good morning when I leave for work. On the corner, there is a small restaurant that serves delicious noodles. I eat there every Friday evening. There is a bus stop right in front of my building, which makes it easy to go anywhere in the city. The only problem is that the street gets noisy on weekends because of the traffic. But overall, I love my neighborhood because it has everything I need and the people are kind.` },
  { title: "A Rainy Day", section: "lifestyle", cefrLevel: "A2", body: `Yesterday was a very rainy day. When I woke up, I could hear the rain on my window. I looked outside and the sky was dark and grey. I put on my raincoat and took my umbrella to go to work. The streets were wet and there were many puddles. I had to walk carefully so my shoes did not get too wet. At the bus stop, everyone was standing under the shelter trying to stay dry. The bus was late because of the rain, so I had to wait for twenty minutes. When I arrived at work, my trousers were a little wet. I dried them with a towel from the bathroom. During lunch, I stayed inside and ate my sandwich at my desk. I drank hot tea because it was cold. After work, the rain had stopped and there was a beautiful rainbow in the sky. It had seven colors and was very big. I took a photo of it with my phone. When I got home, I changed into dry clothes and made hot soup for dinner. I watched a movie and went to bed early. I hope tomorrow will be sunny.` },
];

// ── Extra B2 passage ──
const B2_EXTRA: Passage[] = [
  { title: "The Rise of Plant-Based Diets", section: "health", cefrLevel: "B2", body: `The global shift toward plant-based eating represents one of the most significant dietary transformations in recent history. Once considered niche or countercultural, vegetarian and vegan diets have entered the mainstream, driven by growing awareness of their environmental, health, and ethical implications. The environmental case for reducing meat consumption is compelling. Livestock farming accounts for approximately fourteen percent of global greenhouse gas emissions, requires vast quantities of water and land, and is a leading cause of deforestation, particularly in tropical regions. Producing a kilogram of beef requires roughly fifteen thousand liters of water and generates nearly thirty kilograms of carbon dioxide equivalent, compared to just three hundred liters of water and less than one kilogram of emissions for the same quantity of vegetables. From a health perspective, well-planned plant-based diets have been associated with lower rates of heart disease, type two diabetes, certain cancers, and obesity. The World Health Organization has classified processed meat as a Group One carcinogen, placing it in the same category as tobacco smoking and asbestos in terms of the strength of evidence linking it to cancer. However, nutritionists emphasize that plant-based diets require careful planning to ensure adequate intake of essential nutrients such as vitamin B12, iron, zinc, and omega-three fatty acids. The food industry has responded to growing demand with an explosion of plant-based alternatives. Companies like Beyond Meat and Impossible Foods have developed products that closely mimic the taste and texture of conventional meat using plant proteins. These products have attracted not only committed vegans but also flexitarians — individuals who primarily eat plant-based foods but occasionally consume animal products. While the environmental and health benefits of reducing meat consumption are well-established, a complete transition to plant-based diets faces significant cultural, economic, and logistical challenges that will take decades to fully resolve.` },
];

const B1_EXTRA: Passage[] = [
  { title: "Recycling at Home", section: "environment", cefrLevel: "B1", body: `Recycling has become an important part of daily life in many countries. Most cities now provide special bins for different types of waste, such as paper, plastic, glass, and organic materials. However, many people are still confused about what can and cannot be recycled. For example, not all plastics are recyclable. Items contaminated with food, such as greasy pizza boxes, usually cannot be processed. To recycle effectively, it is important to clean containers before placing them in the recycling bin and to check your local guidelines. The benefits of recycling are significant. It reduces the amount of waste sent to landfills, conserves natural resources, and saves energy. Manufacturing products from recycled materials typically requires less energy than producing them from raw materials. For instance, recycling aluminum cans saves about ninety-five percent of the energy needed to make new aluminum from ore. Beyond individual actions, companies are increasingly adopting sustainable packaging practices. Many businesses are switching to biodegradable or compostable materials and designing products with their end-of-life in mind. While recycling alone cannot solve the global waste crisis, it is an essential component of a broader strategy that includes reducing consumption, reusing items, and rethinking how products are designed and manufactured.` },
  { title: "Learning a Musical Instrument", section: "education", cefrLevel: "B1", body: `Learning to play a musical instrument is a rewarding but challenging experience. Research shows that playing music has numerous benefits for the brain. It improves memory, enhances coordination, and develops mathematical abilities. Studies have also found that musicians tend to have better listening skills and can concentrate for longer periods. Many people start learning an instrument as children, but it is never too late to begin. Adults who take up an instrument often find it a relaxing hobby that helps reduce stress. The most popular instruments for beginners include the piano, guitar, and ukulele. The piano is often recommended because it provides a visual understanding of music theory. The guitar is popular because it is portable and can be used to play many different styles of music. When starting out, it is important to practice regularly, even if only for fifteen to twenty minutes a day. Consistency is more valuable than occasional long practice sessions. Finding a good teacher can also make a significant difference, although many people successfully learn through online tutorials and apps. One of the greatest joys of learning an instrument is being able to play your favorite songs. It requires patience and dedication, but the sense of achievement when you master a difficult piece is incredibly satisfying.` },
];

const ALL_PASSAGES = [...A2, ...A2_EXTRA, ...B1, ...B1_EXTRA, ...B2, ...B2_EXTRA, ...C1];



async function seed() {
  const client = await pool.connect();
  try {
    console.log(`Seeding ${ALL_PASSAGES.length} reading passages...`);
    for (const p of ALL_PASSAGES) {
      const wordCount = p.body.trim().split(/\s+/).length;
      await client.query(
        `INSERT INTO reading_passage (title, body, cefr_level, section, word_count) VALUES ($1, $2, $3, $4, $5) ON CONFLICT DO NOTHING`,
        [p.title, p.body.trim(), p.cefrLevel, p.section, wordCount],
      );
    }
    console.log(`✅ Seeded ${ALL_PASSAGES.length} passages (A2:${A2.length}, B1:${B1.length}, B2:${B2.length}, C1:${C1.length}).`);
  } finally {
    client.release();
    await pool.end();
  }
}

seed().catch((err) => { console.error("Seed failed:", err); process.exit(1); });
